cn:
  springcloud:
    book:
      config: I am the git configuration file from dev environment. I will edit it. 88889106

config:
  code:
    validate:
      expire: 10
  request:
    iplimit:
      apis: /api/user/register/
      intervalMinutes: 1
      maxRequestCount: 6
  response:
    message:
      seeother: 您频繁进行注册，请求已被拒绝！
      unauthorize: 您的请求没有授权，请登录或注册后再访问！
  email:
    host:
    sender:
      name:
      password:
    templates:
      checkcode:
        title: 注册验证码
        content: 您好，本次登录的验证码为：%s，将在10分钟之后过期

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou_springcloud_task?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名

#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://ServerEurekaA:8761/eureka,http://ServerEurekaB:8762/eureka
  instance:
    prefer-ip-address: true #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        exlude: "*"
